[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
whoami = "1.5"
tokio = { version = "1.28", features = ["full"] }
reqwest = "0.13.2"
public-ip = "0.2.2"