[package]
name = "controller"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.28", features = ["full"] }